#server.port=8082

#spring.datasource.url=jdbc:postgresql://localhost:5432/userservice
#spring.datasource.username=postgres
#spring.datasource.password=anesa2
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.idle-timeout=30000
#spring.datasource.hikari.connection-timeout=30000

#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true

#configuration
spring.application.name=user-service
spring.profiles.active=development
spring.config.import=optional:configserver:http://localhost:8888


