spring.application.name=config-server
spring.profiles.active=local
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/iosmankovi2/volunteer-config-repo.git
spring.cloud.config.server.git.username=iosmankovi2
spring.cloud.config.server.git.password=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


spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.searchPaths=feedback-service, user-service, participation-service, notification-communication-service, activity-service
spring.cloud.config.server.git.clone-on-start=true
