spring.application.name=config-server
spring.profiles.active=local
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/iosmankovi2/volunteer-config-repo.git
spring.cloud.config.server.git.username=${GIT_USERNAME}
spring.cloud.config.server.git.password=${GIT_TOKEN}


spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.searchPaths=feedback_service, user-service, participation-service, notification-communication-service, activity-service
spring.cloud.config.server.git.clone-on-start=true
