spring.application.name=config-server
spring.profiles.active=local
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/krslakjr/volunteer-config-repo
spring.cloud.config.server.git.username=krslakjr
spring.cloud.config.server.git.password=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


spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.searchPaths=feedback-service, user-service, participation-service, notification-communication-service, activity-service, system-events-service
spring.cloud.config.server.git.clone-on-start=true
